#!/bin/bash

# This script promotes osg-version to testing and generates a preliminary list of packages for the release manager

. release-common.sh

##################################
# Promote osg-version to testing #
##################################

for dver in "${dvers[@]}"; do
    for repo in testing prerelease; do
        tag=osg-$majorver-$dver-$repo
        pkg=osg-version-$version-1.$osgver.$dver
        osg-koji latest-pkg $tag osg-version | grep $pkg > /dev/null
        if [ $? -eq 1 ]; then
            echo "Promoting $pkg into $tag..."
            osg-koji tag-pkg $tag $pkg
        else
            echo "$pkg already tagged in $tag"
        fi
    done
done

#############################
# Generate list of packages #
#############################

for branch in "${branches[@]}"; do
    for dver in "${dvers[@]}"; do
        echo "RPM's slated for release in osg-$branch-$dver-release"
        koji-tag-diff osg-$branch-$dver-testing osg-$branch-$dver-release
        echo

        echo "Development builds ahead of testing -- *not* slated for release"
        ./osg-pkgs-behind-tag osg-$branch-$dver-{testing,development}
        echo
    done
done
