#!/bin/bash

# This script promotes osg-version to testing and generates a preliminary list of packages for the release manager

. release-common.sh

# make sure osg-koji is available before starting
check_for_osg_koji

release_tools="osg-pkgs-behind-tag"

for i in $release_tools
do
    check_for_and_add_command $i
    if [[ $? -ne 0 ]];
    then
        echo "Release tool ($i) not present in PATH"
        exit 1
    fi
done

detect_rescue_file

# #############################
# # Generate list of packages #
# #############################

for branch in ${versions[@]}; do
    read -ra dvers <<< $(osg_dvers $branch) # create array of dvers
    for dver in ${dvers[@]}; do
        print_header_with_line "RPMs slated for release in osg-$branch-$dver-testing"
        slated_cmd="koji-tag-diff osg-$branch-$dver-{testing,$(release_tag_name $branch)}"
        slated=$(eval $slated_cmd | tail -n +2)
        if [[ $DRY_RUN -eq 1 ]]; then
            echo $slated_cmd
        else
            echo "$slated"
        fi
        echo

        slist=$(echo "$slated" | perl -lpe 's/(-[^-]+){2}$//' | tr '\n' ' ')
        print_header_with_line "Slated packages in testing behind current development versions"
        run_cmd "osg-pkgs-behind-tag osg-$branch-$dver-{testing,development} -- $slist"
        echo
    done
done

# Don't remove rescue files if user is troubleshooting
if [ $DRY_RUN -eq 0 ]; then
    cleanup_on_success
fi
