#!/bin/bash

# Run this script on an EL6 Fermicloud VM to generate the client tarballs
# and copy them over to UW's AFS

. release-common.sh
detect_rescue_file

if [ $(whoami) != 'root' ]; then
    usage
    die "Script must be run as root"
fi

if [[ $DRY_RUN -eq 0 ]]; then
    echo "Enter username and machine name to use for scp, e.g. matyas@ingwe.cs.wisc.edu"
    read rusermachine
fi

print_header "Preparing tools for tarball generation"
run_cmd "yum -y install git yum-priorities"
pushd /tmp
run_cmd "git clone --depth 1 https://github.com/opensciencegrid/tarball-client"

# drop upcoming from versions since they don't get their own tarballs
versions=(${versions[@]/upcoming/})

# Build tarballs
for ver in ${versions[@]}; do
    branch=$(osg_release $ver)
    print_header "Generating $branch tarballs"
    run_cmd "/tmp/tarball-client/make-client-tarball --osgver=$branch --version=$ver --all --prerelease"
    archs="x86_64"
    for arch in $archs; do
        tarball_dir="tarballs/$branch/$arch"
        run_cmd "mkdir -p $tarball_dir"
        run_cmd "mv osg*client-$branch*$arch*.tar.gz $tarball_dir"
    done
done

print_header "Copying tarballs to $rusermachine"
rsync -av tarballs/ $rusermachine:/p/vdt/public/html/tarball-client/
check_file_transfer_rc $?
popd

# Don't remove rescue files if user is troubleshooting
if [ $DRY_RUN -eq 0 ]; then
    cleanup_on_success
fi
