#!/bin/bash

# Compare the list of packages in pre-release for against the release
# list put together by the OSG Release Coordinator

. release-common.sh

final_msg=""

# Make pipes so we can diff package lists
mkfifo prerelease
mkfifo slated

for ver in ${versions[@]}; do
    branch=$(osg_release $ver)
    read -ra dvers <<< $(osg_dvers $ver) # create array of dvers
    for dver in ${dvers[@]}; do
        tag_prefix=osg-$branch-$dver
        prerel_tag=$tag_prefix-prerelease
        rel_tag=$tag_prefix-release

        # Get lists of packages from release list and compare them to what's currently in prerelease
        osg-koji list-tagged --quiet $prerel_tag | awk '{print $1}' > prerelease &
        awk "/^RPMs.*$rel_tag/ {flag=1;next} /^[[:space:]]*$/ { flag=0 } flag { print }" release-list > slated &
        pkg_diff=$(diff -u slated prerelease)

        # If there are differences between prerelease and slated, print them at the end
        if [[ -n $pkg_diff ]]; then
            final_msg=$(printf "%s\n\n$(print_header "Package diff in $prerel_tag")\n%s" \
                        "$final_msg" "$pkg_diff")
        fi
    done
done

if [[ -z $final_msg ]]; then
    print_header "Pre-release matches the slated package list. Please continue with the rest of the release process."
else
    echo "$final_msg" | tail -n +3
fi

rm prerelease slated

cleanup_on_success
