#!/bin/bash

# This script encompasses Day 1 of https://twiki.opensciencegrid.org/bin/view/SoftwareTeam/HowToCutRelease

. release-common.sh

for ver in ${versions[@]}; do
    branch=$(osg_release $ver)
    read -ra dvers <<< $(osg_dvers $ver) # create array of dvers
    for dver in ${dvers[@]}; do
        tag="osg-$branch-$dver-prerelease"
        print_header "\nContents of $tag:"
        run_cmd "osg-koji list-tagged --quiet $tag | awk '{print \$1}'"
    done
done

cleanup_on_success
