#!/bin/bash

# Solves 404 error messages when retrieving packages for building the tarballs

. release-common.sh

# make sure osg-koji is available before starting
check_for_osg_koji

detect_rescue_file

for branch in ${versions[@]}; do
    # drop upcoming from versions since they don't get their own tarballs
    # we don't use release-build for OSG 23
    if [[ $branch = *-upcoming ]] || [[ $branch == 23-main ]]; then
        continue
    fi
    read -ra dvers <<< $(osg_dvers $branch) # create array of dvers
    for dver in ${dvers[@]}; do
        run_cmd "osg-koji regen-repo osg-$branch-$dver-release-build" # avoid pkg 404 errors
    done
done

# Don't remove rescue files if user is troubleshooting
if [ $DRY_RUN -eq 0 ]; then
    cleanup_on_success
fi

