#!/bin/bash

# Unlock the release repos and move the pre-release packages into them.
# Create a version-specific release tag (for non-data-only releases)
# Lock the release repos


. release-common.sh

check_for_osg_koji

detect_rescue_file

for ver in ${versions[@]}; do
    branch=$(osg_release $ver)
    if [[ $branch == 'upcoming' ]]; then
        ver=$upcoming_version
    fi
    read -ra dvers <<< $(osg_dvers $ver) # create array of dvers
    for dver in ${dvers[@]}; do
        prerelease_repo=osg-$branch-$dver-prerelease
        release_repo=osg-$branch-$dver-release

        # Push from pre-release to release
        print_header "Unlocking $release_repo"
        run_cmd "osg-koji edit-tag --unlock $release_repo"
        echo

        print_header "Moving packages from $prerelease_repo to $release_repo"
        pkgs_to_release $branch $dver > move-to-$branch-release-$dver
        if [ -s move-to-$branch-release-$dver ]; then
            run_cmd "xargs --arg-file move-to-$branch-release-$dver osg-koji move-pkg $prerelease_repo $release_repo"
        fi
        echo

        if [ $DATA -eq 0 ]; then
            # Create new release repo for non-$data releases
            versioned_release_repo=osg-$branch-$dver-release-$ver
            print_header "Cloning $release_repo to $versioned_release_repo"
            run_cmd "osg-koji clone-tag --all $release_repo $versioned_release_repo"
            echo
        fi

        # Lock repos (data-only releases leave the versioned repos untouched
        # for historical integrity)
        for repo in $release_repo $versioned_release_repo; do
            print_header "Locking $repo"
            run_cmd "osg-koji edit-tag --lock $repo"
            echo
        done

    done

done

# Don't remove rescue files if user is troubleshooting
if [ $DRY_RUN -eq 0 ]; then
    cleanup_on_success
fi
