#!/bin/bash

usage () {
    echo "usage:"
    echo "  $(basename "$0") NON_UPCOMING_VERSIONS"
    exit
}

[[ $1 =~ ^[3-9]\.[0-9]+\.[0-9]+$ ]] || usage

cd /p/vdt/public/html/tarball-client
for ver in "$@"; do
    major_ver="${ver%.*}"
    ssh osgcollab@hcc-osg-software.unl.edu mkdir -p /usr/local/repo/tarball-install/$major_ver/$ver
    scp -p $major_ver/*/osg-wn-client-$ver*gz osgcollab@hcc-osg-software.unl.edu:/usr/local/repo/tarball-install/$major_ver/$ver
done
ssh osgcollab@hcc-osg-software.unl.edu bin/mk-sims.sh
for ver in "$@"; do
    major_ver="${ver%.*}"
    ssh osgcollab@hcc-osg-software.unl.edu "cd /usr/local/repo/tarball-install; ls -l $major_ver/*latest*"
done
echo 'Verify the "latest" symlinks point to the version(s) just installed'
