#!/bin/bash

. release-common.sh

if [[ $DRY_RUN -eq 0 ]]; then
    echo "Enter username and machine name to use for scp, e.g. matyas@ingwe.cs.wisc.edu"
    read rusermachine
fi

echo "Enter the directory containing the tarballs:"
read tarball_src
if [ ! -d $tarball_src ]; then
    echo "Directory not found: $tarball_src"
    exit 1
fi

for branch in ${versions[@]}; do
    # drop upcoming from versions since they don't get their own tarballs
    if [[ $branch = *-upcoming ]]; then
        continue
    fi
    archs="x86_64"
    for arch in $archs; do
        tarball_dest="tarballs/$branch/$arch"
        mkdir -p $tarball_dest
        mv $tarball_src/osg*client-$(ver_tag $branch)*$arch*.tar.gz $tarball_dest
    done
done

print_header "Copying tarballs to $rusermachine"
rsync -av tarballs/* $rusermachine:/p/vdt/public/html/tarball-client/
check_file_transfer_rc $?
