#!/bin/bash

. release-common.sh

######################################
# Generate full list of packages in: #
#   - release behind testing, and    #
#   - testing behind development     #
######################################

for branch in "${branches[@]}"; do
    for dver in "${dvers[@]}"; do
        echo "RPMs slated for release in osg-$branch-$dver-release"
        ./osg-pkgs-behind-tag osg-$branch-$dver-{release,testing}
        echo

        echo "Development builds ahead of testing -- *not* slated for release"
        ./osg-pkgs-behind-tag osg-$branch-$dver-{testing,development}
        echo
    done
done
